### PR TITLE
updated readme and join.html

### PR DESCRIPTION
**Pull request by yashjain1974**

### CODE REVIEW

**Comment by Hrk-Web** [comment]
@yashjain1974  please describe that what work you did??

**Comment by yashjain1974** [comment]
Bro I have correct some spelling mistakes and capitalise letters

**Comment by Hrk-Web** [comment]
you added  ' :- ' after " title of tournament " that we don't want.
and in the readme.md file having different meaning of dots and capital and small letters, it is for our convenience

**Comment by Hrk-Web** [comment]
if you want to contribute then add some features

**Pull request closed without merging**
